alerts:
  critical_threshold: 1
  email_recipients:
  - security@company.com
  enabled: true
  slack_webhook_url: https://hooks.slack.com/...
  teams_webhook_url: ''
api:
  cors_origins:
  - '*'
  host: 0.0.0.0
  port: 8080
  rate_limit_enabled: true
  rate_limit_requests: 100
bitbucket:
  app_password: your-app-password
  base_url: https://api.bitbucket.org/2.0
  username: your-username
  workspace: your-workspace
cve_sources:
  nvd_api_key: your-nvd-api-key
  oss_index_token: your-oss-token
  oss_index_username: your-oss-username
  snyk_api_token: your-snyk-token
database:
  endpoint_url: null
  region: us-east-1
  table_prefix: vuln-scanner
debug: false
environment: development
logging:
  backup_count: 5
  file_path: logs/vulnerability_scanner.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10485760
scanning:
  max_concurrent_scans: 5
  retry_attempts: 3
  retry_delay: 60
  scan_timeout: 300
  schedule: 0 2 * * *
