version: '3.8'

services:
  vulnerability-scanner:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BITBUCKET_WORKSPACE=${BITBUCKET_WORKSPACE}
      - BITBUCKET_USERNAME=${BITBUCKET_USERNAME}
      - BITBUCKET_APP_PASSWORD=${BITBUCKET_APP_PASSWORD}
      - NVD_API_KEY=${NVD_API_KEY}
      - SNYK_API_TOKEN=${SNYK_API_TOKEN}
      - OSS_INDEX_USERNAME=${OSS_INDEX_USERNAME}
      - OSS_INDEX_TOKEN=${OSS_INDEX_TOKEN}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DYNAMODB_TABLE_PREFIX=${DYNAMODB_TABLE_PREFIX:-vuln-scanner}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./configs:/app/configs:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Optional: Local DynamoDB for development
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data/"]
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    profiles:
      - dev

volumes:
  dynamodb_data: